### ISSUE TITLE
Truffle Graal Runtime: Check for thread-safety

### ISSUE THREAD

**Issue by chumer** [graalvm/graal-core#103]
The goal is to go over all the Graal Truffle runtime API and document each relevant method whether it needs to be thread-safe or not and whether it is thread-safe. Preferably we can fix most issues while we document it.

Issues already reported:
- Compilation queue was reported to be not thread-safe. Its still possible that multiple compilations of the same call target are queued.
- Double checked locking with non-volatile fields for instrumentation initialization

**Comment by eregon** [comment]
See https://github.com/graalvm/graal-core/pull/102 and https://github.com/graalvm/truffle/pull/105 for some double-checked locking fixes.

**Comment by dougxc** [comment]
What's the status on this?

**Comment by eregon** [comment]
I'll let @chumer summarize the general progress.
On my part I fixed a couple issues in PrimitiveValueProfile and AssumedValue.

**Comment by chumer** [comment]
I think there is still some problems in GraalTruffleRuntime that should be adressed. However they are already tracked elsewhere. So we can safely close this one.
