### ISSUE TITLE
check for labels

### ISSUE THREAD

**Issue by dougxc** [graalvm/graal-core#11]
Every pull request to graal-core should be labeled with either `oracle-emp` or `oca-signed`. We need a [status check](https://developer.github.com/v3/repos/statuses/) to enforce this.

**Comment by sanzinger** [comment]
I am not clear so far, but do we want to 
a) force the user to specify a label during creation or
b) assign the label according to a database automatically after the pull request was created?

I think a) is not possible.
For a) we need to hook on [pull_request hook](https://developer.github.com/v3/activity/events/types/#pullrequestevent) which then assigns the labels to the pull request according to a database of usernames/email.

**Comment by dougxc** [comment]
Automatically assigning based on a database would be ideal but I don't know where we would host such a database. One option is a separate repo in the graalvm project to host the database. I think option a) is sufficient for now. Why do we need to force specifying the label during PR creation? The checks are only run after the PR is requested right?

**Comment by sanzinger** [comment]
As Aleksandar suggested to add it to a travis build to actually check whether the user is either an oracle employee or has oca-signed.

* If user is in the database, the label gets assigned and build continues;
* If user is not in the database, the travis build fails immediately.

The database could be a csv file could be hosted in a separate repository in github, where travis build is looking at.

If the travis run fails due to missing tag, someone has to update the database and restart the travis build.

**Comment by axel22** [comment]
Just a few more thoughts. In the *a* approach: travis build has information about the PR in an env var: [`TRAVIS_PULL_REQUEST`](https://docs.travis-ci.com/user/environment-variables/). Travis build can then use the [GitHub API](https://developer.github.com/v3/) to find out [more about the PR](https://developer.github.com/v3/pulls/#get-a-single-pull-request) and fail on missing labels, or [query a repo with a user list text file](https://developer.github.com/v3/repos/contents/).

As for *b* approach, a Travis build could additionally [assign the label](https://developer.github.com/v3/pulls/#update-a-pull-request).

I'd say both are relatively easy to accomplish.

**Comment by sanzinger** [comment]
Yes, I think, a travis buildstep would be okay. Just got a few links from @zapster which show how Google is dealing with it. In a nutshell, they host an external job at google which chronically checks open pull requests and updates the labels. Their database is a "spreadsheet".

Their script: https://github.com/angular/google-cla-verifier-for-github
How it looks like in an PR: https://github.com/google/material-design-lite/pull/4033#issuecomment-175608946

**Comment by dougxc** [comment]
We now have the oca bot implemented.
