### ISSUE TITLE
Improve and speed-up common ancestor

### ISSUE THREAD

**Issue by thomaswue** [graalvm/graal-core#118]
See changeset and comment https://github.com/graalvm/graal-core/commit/ada793a36a26c5140ec79afe1a1c011fc3d9c87d#commitcomment-16616230

**Comment by axel22** [comment]
It would be helpful if had some *micro*benchmarking harness to experiment with the alternatives on synthetic examples. Do we already have something like this?

**Comment by thomaswue** [comment]
We have been using JMH, @dougxc can show you this code. The issue is that for some of these more global aspects like how much caching the results gains us on a large application is hard to capture in a micro benchmark setting.

**Comment by axel22** [comment]
Ok, I'll talk to Doug, and do both the microbenchmarking and large applications to validate the changes.

**Comment by thomaswue** [comment]
This issue also needs to solve https://github.com/graalvm/graal-core/commit/ada793a36a26c5140ec79afe1a1c011fc3d9c87d#commitcomment-16626209

**Comment by axel22** [comment]
The `meet` operation should be commutative after:

https://github.com/graalvm/graal-core/commit/3c564dee2e97dd40b4580bf7b5266f3e909bd44c

After some discussion and one-off tests, we found that we don't have good use-cases where common ancestor lookup is expensive - benchmarks and compile-the-world revealed that `meetTypes` finishes very early (1-2 recursive calls), and I was only able to construct an artificial case where this gets slow. The conclusion with @dougxc was to delay further action until we have a real use-case.
