### ISSUE TITLE
mx: refactor mx_graal_{8,9}.py to avoid code duplication

### ISSUE THREAD

**Issue by zapster** [graalvm/graal-core#13]
Currently there is lots of code duplication in [mx.graal-core/mx_graal_8.py](https://github.com/graalvm/graal-core/blob/master/mx.graal-core/mx_graal_8.py) and [mx.graal-core/mx_graal_9.py](https://github.com/graalvm/graal-core/blob/master/mx.graal-core/mx_graal_9.py). This makes mx.graal-core changes cumbersome and error-prone. We should factor out the common parts and keep the files as minimal as possible.

**Comment by dougxc** [comment]
Looking at a diff between mx_graal_8.py and mx_graal_9.py shows a large number of differences so I'm not sure how much commonality there is. Only the `UnitTestRun` and `MicrobenchRun` classes are identical. Every other class and method has some differentiation for jvmci-8 and jvmci-9.

**Comment by zapster** [comment]
I guess it is mostly about changes to `mx gate` like adding/removing tasks or flags to tasks (cf #14). The biggest blocker is the `VM` vs. `JVMCIMode` situation. Maybe avoiding duplication gets easier in the future. Feel free to close the issue.

**Comment by dougxc** [comment]
Ok. We can reassess the potential savings of commoning later.
