### ISSUE TITLE
Could we have an update of the Truffle import whenever there is a new Truffle released?

### ISSUE THREAD

**Issue by eregon** [graalvm/graal-core#138]
Currently, there is no such thing and finding which Graal revision is compatible with a given Truffle release (let alone a specific revision) is a guess work.

Ideally, we would have a clearer statement and extended compatibility but it seems the first step is, when Truffle is released, there should quickly be a Graal version with the updated import, and also tested to at least make sure the graal-truffle related integration works correctly.

**Comment by dougxc** [comment]
We now tag all the components at each GraalVM release. Does that cover your needs @eregon ?

**Comment by eregon** [comment]
@dougxc Yes, it does, as long as a GraalVM release uses a Truffle release (otherwise maven releases do not match graalvm truffle versions), thanks!
