### ISSUE TITLE
Miscompilation with Graal on Loop and Array code

### ISSUE THREAD

**Issue by smarr** [graalvm/graal-core#191]
I got a long standing issue that one of my benchmarks is seemingly miscompiled by Graal.

The benchmark fails sporadically. I assume the interpreter being correct since when running on Graal (with splitting etc.) but restricting compilation to a non-existing method, the code runs correctly.

To reproduce:

```bash
git clone https://github.com/smarr/SOMns
cd SOMns
ant
export JVMCI_BIN=$YOUR_PATH_TO_YOUR_GRAAL_JVMCI_BINARY
export GRAAL_FLAGS=$ANY_GRAAL_FLAGS_PERHAPS
./debug -o "GraphSearch>>#breadthFirstSearch:" core-lib/Benchmarks/Harness.som GraphSearch  250 0 30
```

This restricts the compilation to one of the problematic methods.
The benchmark is implemented in [core-lib/Benchmarks/GraphSearch.som](https://github.com/smarr/SOMns-corelib/blob/master/Benchmarks/GraphSearch.som#L78).

To verify without any compilation:
```
./debug -o "NON_EXISTING:" core-lib/Benchmarks/Harness.som GraphSearch  250 0 30
```

**Comment by smarr** [comment]
To reproduce with the latest Graal version, make sure the SOMns Truffle jar is the only one on the bootclasspath.

The raw command line for Java looks something like this:

```bash
$ export SOMNS=~/SOMns
$ export GRAAL_DIST=~/graal-core/mxbuild/dists
$ ~/graal-jvmci-8/jdk1.8.0_65/product/bin/java -server -Dgraal.TruffleCompileOnly="GraphSearch>>#breadthFirstSearch:" -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -d64 -Djvmci.class.path.append=$GRAAL_DIST/graal-options.jar:$GRAAL_DIST/graal-nodeinfo.jar:$GRAAL_DIST/graal-serviceprovider.jar:$GRAAL_DIST/graal-api.jar:$GRAAL_DIST/graal-compiler.jar:$GRAAL_DIST/graal-runtime.jar:$GRAAL_DIST/graal-hotspot.jar:$GRAAL_DIST/graal-truffle.jar:$GRAAL_DIST/graal-truffle-hotspot.jar  -Djvmci.Compiler=graal -Xbootclasspath/a:$SOMNS/build/classes:$SOMNS/libs/truffle/mxbuild/dists/truffle-api.jar:$SOMNS/libs/truffle/mxbuild/dists/truffle-debug.jar:$SOMNS/libs/jline-2.11.jar:$SOMNS/libs/websocket/dist/websocket.jar:$SOMNS/libs/minimal-json/build/minimal-json.jar som.VM --platform $SOMNS/core-lib/Platform.som --kernel $SOMNS/core-lib/Kernel.som $SOMNS/core-lib/Benchmarks/Harness.som GraphSearch 250 0 30
```

**Comment by gilles-duboscq** [comment]
OK, Thanks, i will look at it again tomorrow

**Comment by smarr** [comment]
This issue is most likely solved. Thanks to @gilles-duboscq, who found the actual bug in my code :( Sorry for the ghost chase.

`@CompilationFinal` is easily used wrong:
https://github.com/smarr/SOMns/commit/32d0caa5e444c8a976ee188336b6927bbc47d062

**Comment by woess** [comment]
good that we implemented support for `@CompilationFinal(dimensions=0)` :)
