### ISSUE TITLE
Assertion Failure in MonitorSnippets.java:550

### ISSUE THREAD

**Issue by smarr** [graalvm/graal-core#201]
I got trouble with the latest Graal core, lowering the MonitorSnippet fails with `monitorenterNode.object().stamp()` being null.

Specifically, the assertion in [MonitorSnippets.java on line 550](https://github.com/graalvm/graal-core/blob/master/graal/com.oracle.graal.hotspot/src/com/oracle/graal/hotspot/replacements/MonitorSnippets.java#L550) fails.

This can be reproduced as follows:

```
git clone https://github.com/smarr/SOMns
cd SOMns
ant
export JVMCI_BIN=$YOUR_PATH_TO_YOUR_GRAAL_JVMCI_BINARY
export GRAAL_FLAGS=$ANY_GRAAL_FLAGS_PERHAPS
./debug core-lib/Benchmarks/AsyncHarness.som Savina.ThreadRing 100 25  100:100000
``` 

Or, without using the `som` script:

```
export SOMNS=~/SOMns
export GRAAL_DIST=~/graal-core/mxbuild/dists
~/graal-jvmci-8/jdk1.8.0_65/product/bin/java -server  -XX:+UnlockExperimentalVMOptions -esa -ea -XX:+EnableJVMCI -d64 -Djvmci.class.path.append=$GRAAL_DIST/graal.jar -Djvmci.Compiler=graal -Xbootclasspath/a:$SOMNS/build/classes:$SOMNS/libs/truffle/mxbuild/dists/truffle-api.jar:$SOMNS/libs/truffle/mxbuild/dists/truffle-debug.jar som.VM --platform $SOMNS/core-lib/Platform.som --kernel $SOMNS/core-lib/Kernel.som $SOMNS/core-lib/Benchmarks/AsyncHarness.som Savina.ThreadRing 100 25  100:100000
```

Disabling assertions does not show any obvious problems, but, I assume the assertion is there for a reason.

**Comment by smarr** [comment]
Just updated graal-core to the latest version, and the issue still persists:

https://gitlab.soft.vub.ac.be/stefan.marr/SOMns/builds/1040

**Comment by smarr** [comment]
Just to confirm, a run without assertions enabled again shows no issues. I assume, that means, that the `null` for the monitor object is not actually ever executed (if the failing assertion means that some code path is compiler with the monitor object being know to be `null`)

**Comment by dougxc** [comment]
I've determined the underlying problem (locking an auto boxed object) and managed to write a test case to reproduce it. Currently working on a solution.

**Comment by smarr** [comment]
Hmm, are you saying I am locking somewhere in my code on something like `int` or `double`?

**Comment by dougxc** [comment]
Yes. I believe the locking operation is here: https://github.com/smarr/SOMns/blob/master/src/som/interpreter/actors/SPromise.java#L343

However, that's not a problem. This is a bug in how Graal handles stamp updating in the context of the boxing snippets.

**Comment by smarr** [comment]
Ugh, yeah, indeed, I forgot that part. Hmm, that's a rather tricky bit to begin with. Should probably also rethink the locking there.

Thanks!

**Comment by smarr** [comment]
I can confirm this is fixed with https://github.com/graalvm/graal-core/commit/9ab4bfa8ed7f8e72c67a60f030aa774ceb726e00.

Thanks a lot!
