### ISSUE TITLE
Investigate performance issues on JRuby + invokedynamic

### ISSUE THREAD

**Issue by dougxc** [graalvm/graal-core#202]
Investigate why the performance of selected JRuby benchmarks is slower on Graal than C2. See http://mail.openjdk.java.net/pipermail/graal-dev/2016-August/004502.html for more detail.

**Comment by headius** [comment]
For the moment I've backed off to a simple numeric loop in Ruby, to try to at least get a basic case to optimize like I expect.

```ruby
def foo
  i = 0
  while i < 10_000_000
    i+=1
  end
end

loop do
  t = Time.now
  foo
  puts Time.now - t
end
```

The loop and all calls it makes appear to inline properly, but judging by the assembly and GC logs it's still allocating a box for every Fixnum value. For the moment I've got some println logging in PEReadEliminationClosure. It seems to show that the Fixnum value stores are not being elided.

So a question...if a numeric loop with our boxed RubyFixnum gets completely inlined, should I expect PEA to eliminate the boxes? What would prevent that from happening?

**Comment by headius** [comment]
FWIW, here's the bytecode for this "foo" loop method: https://gist.github.com/headius/bbf80f8dcca87cd651b7d67398c0190a

There's a few indy calls, but they all appear to inline ok. My understanding of Graal's PEA is that it should eliminate these allocations, but it doesn't appear to.

**Comment by dougxc** [comment]
@lukasstadler , can you please have a look at this

**Comment by headius** [comment]
I've output IGV XML for this method here: https://www.dropbox.com/s/hfjfumtj6bc08ha/jruby_foo_loop.xml?dl=0

It's not clear to me why the Alloc are there, but I'm just getting familiar with IGV for the first time.

**Comment by headius** [comment]
We made a couple discoveries today:

* The LambdaForm implementation of guardWithTest profiles branches using a piece of code that C2 intrinsifies and Graal does not (`MethodHandleImpl.profileBoolean`). That profiling can be disabled by setting `java.lang.invoke.MethodHandle.PROFILE_GWT=false`, which improves the loop benchmark about 30%.
* Graal's PEA may be too conservative, assuming identity requirements along unfollowed paths. This appears to prevent it from eliminating the box in the Ruby loop. By forcing VirtualObjectNode to always have `hasIdentity=false` the loop benchmark improves substantially.

With these two changes in place, the loop is 7x-8x faster, much more in line with what I expected to see.

**Comment by headius** [comment]
FWIW the above changes also appear to help a Mandelbrot benchmark I mentioned briefly in my post...it is now many times faster than on C2 (5x with our Fixnum cache in place, 8-10x with it removed).

Seems like there's some really good opportunities here for improving Graal.

**Comment by headius** [comment]
I'm shutting down for the day, but here's the final graph with both of the above tweaks in place. It looks much better. My expectation is that with a bit more work we should be able to get the loop to fold completely away.

Thanks to all those who helped me with my first day hacking Graal :-)

https://www.dropbox.com/s/0ysv5w83y7vm41n/jruby_loop_minus_gwt_minus_identity.svg?dl=0

**Comment by lukasstadler** [comment]
One thing I had to do in order to reproduce your results was to disable the fixnum cache - I guess that you also did that?

Concerning the PEA part: Indeed, object identity is the problem here.
A compiler needs to be careful in the face of deoptimization: You cannot expect that you've seen all the code, which means that, as long as there is some reference to an object in the deopt info, the identity could still be relevant.
However, bytecode compilers in HotSpot (including Graal) eagerly clear out locals and stack slots that aren't needed any more, so there are no more references in the deopt info and we could see that the identity really isn't relevant here.
I have a solution locally that takes care of this, let's see if I run into any unexpected problems with it.

**Comment by headius** [comment]
@lukasstadler Yes, I have a patch I'll push to JRuby master that allows disabling the fixnum cache. I had it hardcoded off for the above numbers.

Looking forward to your solution! I guess this is also where we could hack in support for the ValueType annotation, should we want to use it in JRuby?

**Comment by headius** [comment]
@lukasstadler Pushed in jruby/jruby@02739855f9c3aa2d74a44499c8fb488e23346944. Disable with -Djruby.fixnum.cache=false (or -Xfixnum.cache=false passed directly to JRuby's launcher).

**Comment by lukasstadler** [comment]
is there some existing annotation like ValueType that we could piggyback on?

**Comment by headius** [comment]
Hmm...I'm not sure. Ideally it would be something already in JDK so we wouldn't introduce a hard dependency on Graal. I'll take a look around.

FTR here's my totally-not-kosher patch, for anyone else following along:

```diff
diff -r 477b91fd1c04 graal/com.oracle.graal.nodes/src/com/oracle/graal/nodes/virtual/VirtualObjectNode.java
--- a/graal/com.oracle.graal.nodes/src/com/oracle/graal/nodes/virtual/VirtualObjectNode.java	Fri Aug 05 04:31:04 2016 -0700
+++ b/graal/com.oracle.graal.nodes/src/com/oracle/graal/nodes/virtual/VirtualObjectNode.java	Tue Aug 09 12:23:17 2016 -0500
@@ -48,7 +48,7 @@
 
     protected VirtualObjectNode(NodeClass<? extends VirtualObjectNode> c, ResolvedJavaType type, boolean hasIdentity) {
         super(c, StampFactory.objectNonNull(TypeReference.createExactTrusted(type)));
-        this.hasIdentity = hasIdentity;
+        this.hasIdentity = false;//hasIdentity;
     }
 
     public final int getObjectId() {

```

**Comment by headius** [comment]
There might be some other source pattern that we could use to indicate an object does not expect to have identity, like all-private constructors or something.

**Comment by headius** [comment]
Bleh, yeah there's really nothing out there...and it occurs to me that we can't use anything anyone else is using already because it would apply these new identity semantics to legacy types.

**Comment by headius** [comment]
@lukasstadler Can I see the patch you came up with?

**Comment by dougxc** [comment]
I'm currently adding the intrinsics for `MHI.profileBoolean` as well as `MHI.isCompileConstant` and they should show up on github in the next day or two.

We're still investigating the PEA change.

**Comment by lukasstadler** [comment]
Not good - my simple solution was to enable code that was already there, but disabled in a weird way: https://github.com/graalvm/graal-core/blob/master/graal/com.oracle.graal.virtual/src/com/oracle/graal/virtual/phases/ea/PartialEscapeClosure.java#L886 (the hasIdentity flag makes the Arrays.asList part useless).
`Arrays.asList(intArray).contains(intValue)` is a really bad idea :-) and always returns false.
So enabling this code effectively assumes that it's always ok to merge phi values in loops.
I'm surprised that I didn't get any test failures from this...
If I fix this test with a proper "contains" implementation, then it doesn't trigger any more in for this case.

The "hasIdentity" flag is something that we maintain on a per-allocation basis, not only per-type, so we could also make it a property of the allocation somehow, e.g., route the allocation through a special intrinsic method. But the simplest solution is to put an annotation on the type, for sure.
Where could such an annotation live?

**Comment by headius** [comment]
If annotations known to Graal could be pulled out as a separate published artifact, we'd be willing to use them.

Are you saying that your fix is still able to elide the transient JRuby objects from my examples?

**Comment by lukasstadler** [comment]
unfortunately no, it only captures a simpler case like this:
```
Object o;
if (...) {
  o = new Foo(1,2,3);
} else {
  o = new Foo(4,5,6);
}
```
where it would detect that it can merge the two allocations. this doesn't apply to loops, though, because this relies on the original allocations being obviously dead after the merge, which is not the case for the loops in your example.

**Comment by lukasstadler** [comment]
this annotation would probably need to be behind some security checks, because I can imagine that you could play weird tricks by handing such an object into a JDK method.

**Comment by headius** [comment]
I'd like to understand the problem better.

For the loop case, the problem is that the value from within the loop proceeds to escape out of the loop body? I'm trying to understand what it is in my example that causes the Fixnum objects to need identity. They never escape the method.

Even if it did escape, I'm not sure I understand why the allocation would have to happen for each value in the loop. Why doesn't the identity-sensitive object just materialize after the loop has exited?

Are you on the Gitter channel or otherwise available to chat?

**Comment by lukasstadler** [comment]
unfortunately, I'm on CEST and I'll be on vacation for a few days until Tuesday...

the result of the allocation from before the loop is still available after the loop. therefore, someone could go ahead and compare the phi value to the allocation from before the loop, and thus extract information about how many loop iterations happened. there doesn't even need to be code that does this in the graph, even just having the allocations somewhere in debug info could allow this to happen after a deopt.
of course, it's easy to see for a human that this doesn't happen in your simple example, but it's hard to create a generic solution that works with the abstract-interpretation-style iteration that PEA does. during the iteration, it doesn't know whether there are going to be more usages of an allocation.

as far as I can see, C2 also doesn't merge allocations in this case, even though it uses an escape analysis with a global view on the graph.

**Comment by headius** [comment]
Please, enjoy your vacation :-) Answer questions at your leisure.

> someone could go ahead and compare the phi value to the allocation from before the loop

"Someone"? Are we talking about a debug situation? Doesn't debugging disable most of these optimizations anyway?

If we were to have an annotation, where would the check for that go? I am hoping to experiment with that.

Perhaps there could also be a way to configure Graal, when present, so it knows that our objects do not require identity (or some other hint that materialization can be postponed until the object actually escapes a compilation unit).

The potential gains here are tremendous. I think we should try to find a way to make them available to standard JVM languages.

**Comment by headius** [comment]
The other possible cause would be a "null block" somehow getting into instance_exec. However I am unable to cause that to happen from Ruby code.

The `Hash#to_proc` feature was added by @kares in b2cac044d69873405d8bce925b8ff317bce4ff59, apparently the latest in a string of attempts to add it. This version uses a null block body and a null binding. The null binding would cause the reported stack trace. The null body prevents block-unpacking methods like `instance_exec` to fail because there's no body to execute.

I am not sure this is the cause, but in any case this proc needs to be fixed. The proper way to provide a custom block implementation is to implement BlockBody, not Block. I'll take a crack at it.

**Comment by headius** [comment]
As a hack, I modified our RubyFixnum to implement Truffle's ValueType annotation, and modified Graal's PEA to look for it when virtualizing an object. It works, but obviously this is a hacky way to do it.

https://gist.github.com/headius/1c80a6c3395adbfebf301aff2d64facd

This also gets performance back to our best numbers so far.

**Comment by dougxc** [comment]
The intrinsic for `profileBoolean` is now in (https://github.com/graalvm/graal-core/commit/a2f9d6ca9e8fc6697e497b2205a1e49795d2fe35). Can you please test performance with `java.lang.invoke.MethodHandle.PROFILE_GWT=true` Charlie.

**Comment by dougxc** [comment]
@headius , I'm assuming the reported performance regression has been addressed. Please re-open or comment on this issue if it hasn't.
