### ISSUE TITLE
unable to build graalvm releases: cannot determine VC and root

### ISSUE THREAD

**Issue by christhalinger** [graalvm/graal-core#208]
Download a `graalvm` release from the releases tab, e.g.:

https://github.com/graalvm/graal-core/archive/graal-vm-0.16.tar.gz

unzip and try to build it:

```
cthalinger@tw-mbp-cthalinger:~/Downloads/graal-core-graal-vm-0.16$ ~/graalvm/mx/mx
cannot determine VC and root for /Users/cthalinger/Downloads/graal-core-graal-vm-0.16
```

I understand that this is more an `mx` issue but since it's impossible to build `graalvm` releases it should be filed here.

**Comment by dougxc** [comment]
Since the addition of [big repo](https://github.com/graalvm/mx/commit/58c328c19531d62b7d424f80e35f089b021a0184) support, I think a dependence on VC is unavoidable. As a workaround, you can clone with `--depth=1`. For example:
```
git clone --depth=1 https://github.com/graalvm/graal-core.git
```

**Comment by christhalinger** [comment]
@dougxc and I had an offline conversation about this and I still believe building from a source tar should be supported.

**Comment by dougxc** [comment]
Ok, source tar building will be possible when https://github.com/graalvm/mx/issues/120 is resolved.
