### ISSUE TITLE
WeakReference::get() read is elminated from a loop

### ISSUE THREAD

**Issue by theRealAph** [graalvm/graal-core#223]
public volatile Object referent;
    public final WeakReference<Object> ref;
    public final ReferenceQueue<Object> refQueue;

    public WeakReferenceTest() {
        referent = new Object();
        refQueue = new ReferenceQueue<>();
        ref = new WeakReference<>(referent, refQueue);
    }

    @Actor
    public void actor1() {
        while (ref.get() != null) {
            // burn!
        }
    }

So, actor1 is spinning in a loop, waiting for ref.get() to become
null.  This won't happen until a GC, and this will be a safepoint.
However, the code Graal generates is:

  0x0000007f8546e5f0: mov	x0, #0x7000                	// #28672
                                                ;   {poll}
  0x0000007f8546e5f4: movk	x0, #0x926b, lsl #16
  0x0000007f8546e5f8: movk	x0, #0x7f, lsl #32  ; ImmutableOopMap{c_rarg1=Oop }
                                                ;*aload_0 {reexecute=1 rethrow=0 return_oop=0}
                                                ; - org.openjdk.jcstress.tests.interrupt.WeakReferenceTest::actor1@0 (line 63)

  0x0000007f8546e5fc: ldr	wzr, [x0]       ;   {poll}
  0x0000007f8546e600: b	0x0000007f8546e5f0

This is an infinite loop with a safepoint check in the middle.
Graal apparently doesn't believe that values can change from non-null
at a safepoint.  C2 seems to treat safepoints specially in this
regard.

It's necessary to specify `-XX:+UseParallelGC ` to see this effect in JDK9.

**Comment by tkrodriguez** [comment]
Yes we probably need to model this more carefully.  C2 uses a MemBarCPUOrder which is just an compiler barrier that emits no code.  We could probably just keep the read as a FixedNode instead.  @gilles-duboscq @rschatz Do you think there's a better way for this?

**Comment by tkrodriguez** [comment]
Also I think the reason you need to switch to UseParallelGC is that with G1 there are barrier operations associated with the read which keep it fixed.

**Comment by theRealAph** [comment]
On 21/11/16 18:25, Tom Rodriguez wrote:
> Also I think the reason you need to switch to UseParallelGC is that with G1 there are barrier operations associated with the read which keep it fixed.

Yes, that's exactly the reason.

**Comment by tkrodriguez** [comment]
Actually I get a bad graph no matter which GC is selected.  The real problem is that read elimination will happily eliminate the read in the loop once the loop has been peeled.  I think we have to emit a MemBarNode early against Reference.referent to make sure it appears to be killed for all the other optimization phases.

**Comment by rschatz** [comment]
Perhaps we should just treat `Reference.referent` as if it was volatile?

The thing is, independent of the compiler, you could in probably produce the same bug with a regular Java field and two threads. There the solution would be to make the field volatile.

**Comment by theRealAph** [comment]
Even if the JMM allows us to transform something like

  `while (x.y == null);`

into

  `if (x.y == null)
    for(;;);`

it's still probably a very unwise thing to do.

**Comment by tkrodriguez** [comment]
That's perfectly legal and correct under the jmm.  In the absence of synchronizing constructs I can assume that value is unchanged or at least that I'm not required to see any updates to it.  Otherwise it would be impossible to optimize loop invariant memory operations.  C2 will do the exact same thing for that pattern.

```  0x0000000109abd1f6: mov    ebp,DWORD PTR [r10+0x68]  ;*getstatic a {reexecute=0 rethrow=0 return_oop=0}
                                                ; - l::main@0 (line 4)

  0x0000000109abd1fa: test   ebp,ebp
  0x0000000109abd1fc: jne    0x0000000109abd206  ; OopMap{off=30}
                                                ;*goto {reexecute=1 rethrow=0 return_oop=0}
                                                ; - l::main@6 (line 4)

  ;; B2: #	B2 <- B1 B2  top-of-loop Freq: 1e-35

  0x0000000109abd1fe: test   DWORD PTR [rip+0xfffffffffca96dfc],eax        # 0x0000000106554000
                                                ;*goto {reexecute=0 rethrow=0 return_oop=0}
                                                ; - l::main@6 (line 4)
                                                ;   {poll}
  0x0000000109abd204: jmp    0x0000000109abd1fe```

For the case of referent we need to handle it specially, sort of like a volatile but only affecting the referent field itself.

**Comment by theRealAph** [comment]
Mmm. Grumble. OK.

**Comment by theRealAph** [comment]
I have a patch which seems to work.  It involves inserting a membar in
just the right place when lowering the field access in
lowerLoadFieldNode().  HotSpot does this in
`LibraryCallKit::inline_reference_get():`
 
```
  // Add memory barrier to prevent commoning reads from this field
  // across safepoint since GC can change its value.
  insert_mem_bar(Op_MemBarCPUOrder);
```

Unfortunately we can't do likewise because
jdk.vm.ci.code.MemoryBarriers does not have a CPU-only memory barrier.
Inserting a LOAD_LOAD barrier does do the trick, but it's stronger
than we need for this purpose.  I suppose I could simply use
MembarNode(0), but that's ugly.

So, what do you think?  At least LOAD_LOAD fixes the bug, even though
it's rather inefficient.  It woud be even better to treat the
Reference.get in the same way as C++ volatile, so that it forces a
read but does not restrict the ordering of other memory accesses in
any way.  Then we'd be generating better code than C2, but I think it
would need new logic elsewhere.

Do you want a pull request with what I've got?

**Comment by theRealAph** [comment]
To my considerable surprise, `MembarNode(0)` does exactly the right thing: it produces a CPU-only barrier. So I guess we should go with that.

**Comment by tkrodriguez** [comment]
Sorry I forgot to update this.  I pushed [this](https://github.com/graalvm/graal-core/commit/307eca21dcb25fb8a252f6df987e330d3ec3b596) to fix this issue.  It's basically just a membar(0) like yours but it only modifies Reference.referent.

**Comment by dougxc** [comment]
So we can close this issue now @tkrodriguez ?

**Comment by tkrodriguez** [comment]
I believe we can.
