### ISSUE TITLE
Building Graal on JDK 9 EA +146

### ISSUE THREAD

**Issue by rahmanusta** [graalvm/graal-core#230]
Hello, I want to try `jaotc `so I'm building, graal-core with JDK9 EA +146, when using `mx vm` command I'm getting;

`Usage: java [options] class [arg...]` ...

What I'm missing here ?

Thanks.

**Comment by dougxc** [comment]
What are you expecting to see? Running `mx vm` is the same as just running `java` without any arguments.

**Comment by rahmanusta** [comment]
:D I'm new on Graal, and if I'm asking this, it might mean that documentation is not clear in that sense.

**Comment by rahmanusta** [comment]
If I could ask you, where can I find the new jaotc tool to try http://openjdk.java.net/jeps/295 ?

Thanks.

**Comment by dougxc** [comment]
Sorry, we strive to make the documentation as helpful as possible.

In terms of jaotc, the best place to ask about this is on the [hotspot-compiler-dev](http://mail.openjdk.java.net/mailman/listinfo/hotspot-compiler-dev) list as the AOT project is being led by the HotSpot compiler group.

**Comment by rahmanusta** [comment]
Thank you @dougxc, I will ask this question to the hotspot-compiler-dev group.  :+1:
