### ISSUE TITLE
Build failure on Debian 8

### ISSUE THREAD

**Issue by vext01** [graalvm/graal-core#235]
Hi,

I'm trying to build graal-0.18 from source on Debian 8. I need to build from source, since this is for a scientific experiment. I'm following the instructions in the README in this project. I've managed to build a JDK with JVMCI support, but Graal doesn't seem to want to accept it. The error message `mx build` gives is:

```
...
Path in --java-home' is not pointing to a JDK (1: Invalid layout of java.lang.Thread at name
Error occurred during initialization of VM
Invalid layout of preloaded class: use -XX:+TraceClassLoading to see the origin of the problem class
)
Please select a default JDK: 
[1] Java 1.8.0_102 (1.8) from /usr/lib/jvm/java-8-openjdk-amd64
[2] Java 1.7.0_79 (1.7) from /usr/lib/jvm/java-7-openjdk-amd64
[3] <other>
```

Here is the script I am using to build all of this. Note that version hash I am using is the hash for (the as yet untagged) graal-0.18 release:

```
JVMCI_VERSION=jvmci-0.23                                                        
MX_VERSION=d9c7efa53f60e4ca493da08438af01f8ca985985                             
GRAAL_VERSION=efb8df47ec55ad5a9c67734ac0b8162e7101cb19 # graal-vm-0.18          
build_graal() {                                                                 
    # A tool called mx is used to clone the code                                
    if [ ! -d ${wrkdir}/mx ]; then                                              
        cd ${wrkdir} && git clone https://github.com/graalvm/mx || exit $?      
        cd mx && git checkout ${MX_VERSION} && cd .. || exit $?                 
    fi                                                                          
                                                                                
    # mx won't listen to CC/CXX                                                 
    ln -sf ${OUR_CC} `dirname ${OUR_CC}`/gcc                                    
    ln -sf ${OUR_CXX} `dirname ${OUR_CXX}`/g++                                  
    GRAAL_PATH=`dirname ${OUR_CC}`:${PATH}                                      
    MX="env PATH=${GRAAL_PATH} python2.7 ${wrkdir}/mx/mx.py --java-home ${OUR_JAVA_HOME}"
                                                                                
    # Build a JVMCI-enabled JDK                                                 
    if [ ! -d ${wrkdir}/graal-jvmci-8 ];then                                    
        hg clone http://hg.openjdk.java.net/graal/graal-jvmci-8                 
    fi                                                                          
    cd graal-jvmci-8 || exit $?                                                 
    hg up ${JVMCI_VERSION} || exit $?                                           
    if [ ! -d ${wrkdir}/graal-jvmci-8/jdk1.8.0 ]; then                          
        ${MX} sforceimports || exit $?                                          
        ${MX} build                                                             
    fi                                                                          
                                                                                
    # Make mx use the jvmci-enabled jdk                                         
    cd ${wrkdir}/graal-jvmci-8                                                  
    JVMCI_JAVA_HOME=`${MX} jdkhome`                                             
    echo "jvmci JAVA_HOME is: ${JVMCI_JAVA_HOME}"                               
    MX="env PATH=${GRAAL_PATH} python2.7 ${wrkdir}/mx/mx.py --java-home ${JVMCI_JAVA_HOME}"
    # Build graal itself                                                        
    cd ${wrkdir}                                                                
    if ! [ -d ${wrkdir}/graal ]; then                                           
        git clone https://github.com/graalvm/graal-core graal || exit $?        
    fi                                                                          
    cd ${wrkdir}/graal && git checkout ${GRAAL_VERSION} || exit $?              
    ${MX} sforceimports || exit $?                                              
    ${MX} || exit $?  # fetches truffle                                         
    ${MX} build || exit $?                                                      
                                                                                
    # remove the symlinks                                                       
    rm `dirname ${OUR_CC}`/gcc `dirname ${OUR_CC}`/g++ || exit $?               
}
```

* `OUR_JAVA_HOME` points to a JDK 8 which is also built from source.
* `OUR_CC` is a binary called `zgcc` which is really gcc-4.9.3, again built from source.

Can anyone spot what I am doing wrong, or is the build broken?

**Comment by rschatz** [comment]
You have a version mismatch between jvmci and the bootstrap jdk. Starting with `jvmci-0.23`, you need to use `jdk-8u111` as bootstrap jdk.

Looks like the README is outdated. I'll update the it.

**Comment by vext01** [comment]
Thanks for the fast reply.

I see. I didn't realise that graal was sensitive to the JDK version. I'll try using a newer one and get back to you.

**Comment by rschatz** [comment]
The problem isn't really Graal, it's the JVMCI jdk. If you try running anything (even `java -version`) out of the jvmci jdk, you'll see that it doesn't work.

The build process of the jvmci jdk doesn't build a full jdk, it just builds the hotspot VM, and copies everything else (e.g. all the libraries) from the bootstrap jdk. Because of that, you need an exact version match between jvmci and the bootstrap jdk.

**Comment by vext01** [comment]
Yep, I knew that it copied a lot from the initial jdk.

So I think you are telling me I need *exactly* jdk-8u111? Or is a newer one OK? There's a few newer builds tagged here:
http://hg.openjdk.java.net/jdk8u/jdk8u/tags

**Comment by rschatz** [comment]
I can't really give you a general answer here. If there is an incompatible change (like between `8u102` and `8u111`), then it's usually neither forward nor backward compatible, but there is no way to find out for sure whether there was such an incompatible change (except trying it out of course).

If you want to be sure, you should use the exact same version, and that's `jdk8u111-b14`.

**Comment by vext01** [comment]
OK, thanks. Will give it a shot.

**Comment by tkrodriguez** [comment]
There was a particular incompatible change in 111 where java.lang.Thread.name changed from a char[] to a String.  So you must use 111 or later with jvmci 0.23. I think there are fixes in transit which will complain if you try to build jvmci with something before 111.  In general though, there's very little upside to using a newer version than the one that corresponds to jvmci bits.

**Comment by vext01** [comment]
Seems to compile OK with 8u111.

It would be nice if we could make it super explicit in the README that an exact version of the JVM is needed.

P.S. The graal-0.18 tag is missing right?

**Comment by dougxc** [comment]
The graal-vm-0.18 tag has now been applied.

**Comment by vext01** [comment]
Thanks
