### ISSUE TITLE
Problem adding match rule for (ReadNode address)

### ISSUE THREAD

**Issue by adinn** [graalvm/graal-core#247]
MatchProcessor needs to generate an import statement for class ValueNode in generated classXXX_MatchStatementSet.java matching as per this discussion on graal-dev:

  http://mail.openjdk.java.net/pipermail/graal-dev/2017-January/004835.html

The fix is a one line change to MatchProcessor.java
```
graal/org.graalvm.compiler.core.match.processor/src/org/graalvm/compiler/core/match/processor/MatchProcessor.java
@@ -521,6 +521,7 @@ public class MatchProcessor extends AbstractProcessor {
             out.println("import " + NodeMatchRules.class.getName() + ";");
             out.println("import " + Position.class.getName() + ";");
             out.println("import " + ServiceProvider.class.getName() + ";");
+            out.println("import " + ValueNode.class.getName() + ";");
             for (String p : info.requiredPackages) {
                 out.println("import " + p + ".*;");
             }
```

**Comment by tkrodriguez** [comment]
fixed as 6224cc5e406256ea92fe619f16353946eeb77bcc.  We don't really want to explicitly import a package we don't use as we'll get style complaints.  The requiredPackages for the ValueNode type should just be added like other types.
