### ISSUE TITLE
GraalVM 0.20 crashes while running Maven

### ISSUE THREAD

**Issue by jonatan-kazmierczak** [graalvm/graal-core#252]
I'm building an application with Maven 3.0.5 running on GraalVM 0.20 on Kubuntu 14.04.
Unfortunately it crashes during execution as follows (BTW, it crashed the same way on GraalVM 0.19):
```
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ ui-tests ---
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f1b58bc7888, pid=13144, tid=0x00007f1b72e3d700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.71-b01-internal-jvmci-0.23 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 6201 JVMCI org.sonatype.aether.util.graph.transformer.NearestVersionConflictResolver.selectVersion(Lorg/sonatype/aether/graph/DependencyNode;Lorg/sonatype/aether/graph/DependencyNode;ILjava/util/Map;Lorg/sonatype/aether/util/graph/transformer/NearestVersionConflictResolver$ConflictGroup;Ljava/util/Map;Lorg/sonatype/aether/graph/DependencyNode;)V (349 bytes) @ 0x00007f1b58bc7888 [0x00007f1b58bc5ba0+0x1ce8] (null)
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /mnt/data/work/ctp/projects/smclient/code/smclient/ui-tests/hs_err_pid13144.log
Loaded disassembler from /mnt/data/opt/graalvm-0.20/jdk/jre/lib/amd64/hsdis-amd64.so
```

I attach [debug output from maven](https://github.com/graalvm/graal-core/files/760623/mvn_on_graalvm_0_20.txt) and [hs_err_pid13144.log.txt](https://github.com/graalvm/graal-core/files/760629/hs_err_pid13144.log.txt)
Please let me know if I can provide more help.

**Comment by dougxc** [comment]
Thanks for the report.

I see that this is an implicit null check for which we have a PcDesc:
```
Registers:
RAX=0x0000000771d1e9d0, RBX=0x000000000000005a, RCX=0x0000000000000000, RDX=0x000000076e9e2840
RSP=0x00007f1b72e3b2a0, RBP=0x00007f1b53ae4000, RSI=0x00000000ee3a3d3a, RDI=0x0000000771d2ee58
R8 =0x00007f1b53ae4000, R9 =0x00007f1b554dd058, R10=0x0000000771d21d50, R11=0x00000007c0018020
R12=0x0000000000000000, R13=0x0000000771d21d78, R14=0x0000000000000000, R15=0x00007f1b6c00a800
RIP=0x00007f1b58bc7888, EFLAGS=0x0000000000010246, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

...

  0x00007f1b58bc7880: mov    rcx,QWORD PTR [rsp+0xe8]
  0x00007f1b58bc7888: mov    rsi,QWORD PTR [rcx]                                                ; OopMap{rcx=Oop rdi=Oop [176]=Oop [192]=Oop [200]=Oop [208]=Oop [216]=Oop [232]=Oop [240]=Oop [248]=Oop off=7403}                                                ;*aload_3 {reexecute=1 rethrow=0 return_oop=0}                                                ; - java.util.IdentityHashMap::get@22 (line 330)
                                                ; - org.sonatype.aether.util.graph.transformer.NearestVersionConflictResolver::selectVersion@47 (line 87)
```

@gilles-duboscq , @rschatz  @tkrodriguez , any ideas as to why the deoptimization path for an implicit exception may be failing, especially given that the deopt info seems to be available?

**Comment by gilles-duboscq** [comment]
I don't think there is a `PcDesc` there: there's a `PcDesc` at the next pc.
I don't think we can reach the path that logs `Implicit null exception at...` for JVMCI nmethods if there's a `PcDesc`. If you look at other places in the disassembly, the `PcDesc` information is usually printed at the previous pc for some reason (maybe to make calls look better?).

**Comment by dougxc** [comment]
Ah yes, I was confused by the layout.

@jonatan-kazmierczak , in the hope that it's only the compilation of `NearestVersionConflictResolver.selectVersion` going wrong, could you try and capture an IGV graph for it by adding these VM options: `-Dgraal.Dump= -Dgraal.MethodFilter=NearestVersionConflictResolver.selectVersion -Dgraal.PrintIdealGraphFile=true`. If we're lucky, that will produce a `runtime-graphs*.bgv` file that you could attach to this issue.

**Comment by jonatan-kazmierczak** [comment]
Here you are: [runtime-graphs-1486575134085_1.bgv.zip](https://github.com/graalvm/graal-core/files/761463/runtime-graphs-1486575134085_1.bgv.zip)

With the mentioned options VM crashed at later stage but with the same problem:
```
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ ui-tests ---
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f4989ede1d0, pid=23253, tid=0x00007f49a58cb700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.71-b01-internal-jvmci-0.23 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 6231 JVMCI org.sonatype.aether.util.graph.transformer.NearestVersionConflictResolver.selectVersion(Lorg/sonatype/aether/graph/DependencyNode;Lorg/sonatype/aether/graph/DependencyNode;ILjava/util/Map;Lorg/sonatype/aether/util/graph/transformer/NearestVersionConflictResolver$ConflictGroup;Ljava/util/Map;Lorg/sonatype/aether/graph/DependencyNode;)V (349 bytes) @ 0x00007f4989ede1d0 [0x00007f4989edc4a0+0x1d30] (null)
```

**Comment by dougxc** [comment]
@thomaswue managed to work out the most likely cause of the crash (a null check guard floating below a read of the guarded value) by inspecting the disassembly from the hs_err file. We're working on fixing this internally and will post an update here once the fix lands in graal-core so you can try it. We'll consider making an earlier GraalVM 0.21 release with the fix as well. Thanks for the useful and detailed report!

**Comment by thomaswue** [comment]
@jonatan-kazmierczak The above mentioned changeset should fix the issue. I will let it open until you are able to confirm it fixed with the next Graal release. Thanks for reporting, this has been very important.

**Comment by jonatan-kazmierczak** [comment]
@thomaswue I've checked the issue on graalvm-0.21-snapshot and it doesn't occur anymore.
So I'm looking forward with optimism to confirm the same on final 0.21 :)

**Comment by thomaswue** [comment]
Excellent, thanks! Yes, one more week is plenty of time to introduce new bugs ;).
