### ISSUE TITLE
floating div/rem nodes

### ISSUE THREAD

**Issue by rschatz** [graalvm/graal-core#41]
Currently the only way Graal can handle division by zero is by relying on the trap from the CPU, triggering a deoptimization and letting the Java interpreter handle the exception. In the usual scenario, where this is a rare case that's fine, we don't actually want to pay any runtime cost for an explicit zero check.

There are a few problems with this approach:
- `IntegerDivNode` has to be a `FixedNode`, preventing some optimizations (e.g. GVN)
- on platforms that don't trap on division by zero (e.g. ARM), the resulting code is not optimal
- Graal can not optimize for the case where the `ArithmeticException` handler is hot

On the other hand, we already have sophisticated handling for null pointer access:
- every `ReadNode` is guarded by a null-checking `GuardNode`
- the `FloatingReadPhase` converts them to `FloatingReadNode`
- the `GuardLoweringPhase` can merge a `FloatingReadNode` and a null check into a (fixed) `ReadNode` with implicit null check

We should use exectly the same mechanism for divisions:
- the `IntegerDivNode` should be replaced by a `DivNode` plus a zero-checking `GuardNode` (both floating)
- the `GuardLoweringPhase` can then merge the guard and a `DivNode` into a (fixed) `TrappingDivNode`

This would solve the above problems:
- the `DivNode` and the guard are separate, and can be separately optimized (e.g. GVNed or completely eliminated)
- ARM can just disable the use of `TrappingDivNode`
- if the `ArithmeticException` is hot, Graal can decide to generate an explicit exception edge instead of the `GuardNode`

**Comment by chrisseaton** [comment]
Does the same idea apply to integer overflow? We don't handle that being hot at the moment do we? I try to work around this in Ruby by using Truffle to specialise an `int+int` that overflows to do a `long+long` instead.

**Comment by rschatz** [comment]
Moved to internal issue tracking system.
