### ISSUE TITLE
Unittests BC_{fd}rem fail on SPARC

### ISSUE THREAD

**Issue by sanzinger** [graalvm/graal-core#46]
The newly introduced unittest combination in BC_{fd}rem fail on SPARC.

SPARC does not provide a FP remainder instruction, we need to implement this ideally as Snippet such as the AArch64FloatArithmeticSnippets.

**Comment by christhalinger** [comment]
Ha!  I had a feeling... :-)

**Comment by zapster** [comment]
just for the record: we should revert #64 when this is fixed

**Comment by sanzinger** [comment]
Fixed with a88f5e83c785a70906c8dfdd419350cc598b9fee
