### ISSUE TITLE
OptionValue.hasDefaultValue doesn't respect overrides

### ISSUE THREAD

**Issue by tkrodriguez** [graalvm/graal-core#60]
The initial version of `OptionValue.hasDefaultValue` included an override check but that disappeared at some point.  What's the intended behaviour of this method?  I would think that `return Objects.equals(getValue(), getDefaultValue());` is the proper implementation of this method but it's not really used in Graal much.  How should this work?  I was trying to use it for another purpose but I realized that it had the wrong semantics so I added `hasBeenSet` instead.

**Comment by dougxc** [comment]
I don't know why this doesn't check overrides - it should. However, `hasDefaultValue` is used in exactly 2 locations and by my reasoning, both of them should actually be using `hasBeenSet`. I'll create a PR to remove the method altogether.

**Comment by dougxc** [comment]
Fixed in https://github.com/graalvm/graal-core/commit/80ae1d469a8c6822620956410c2344a6cc5d1962
