### ISSUE TITLE
Travis gate build times

### ISSUE THREAD

**Issue by tkrodriguez** [graalvm/graal-core#72]
I was looking at adding CTW to the gate and started looking at build times.  The downloading that precedes a gate takes almost 2 minutes which is a lot of time for a 10-15 minute build task.  I think experimenting with caching of .mx/cache would be a good idea.  From the description it doesn't seem like you can test how this affects a build from a pull request but maybe you can.  I'll try it out.

checkstyle takes a surprisingly long time but I think this is mainly because it's run once per project instead of running in batches.  In experiments on my local machine running checkstyle on per project takes almost 2 minutes but running it in 3 batches takes about 15 seconds.  Maybe we should change how this works in the gate?

As far as the javac build we're running on a machine with 2 cores so we do 2 parallel builds.  I'm going to try to increase the default parallelism to 3 in the gate.  If that helps we might want to change the computation of the default parallelism in mx.

/cc @rschatz @gilles-duboscq @dougxc

**Comment by tkrodriguez** [comment]
Caching does seem to work with the pull request but the effects aren't large enough to offset the slowness of the container builds.  Check out the various builds of #74.  The earlier log shows the cache being created and then the last one actually uses it.

Increasing parallelism doesn't seem to help either #73.

**Comment by tkrodriguez** [comment]
I suspect the BuildJavaWithJavac step suffers similar overheads but there's no easy way around that is there?  The output directory for each project is different so there's no way to run a single command to build the result.  The 3 minutes for BuildJavaWithJavac is probably the most annoying delay in our builds at this point.

**Comment by tkrodriguez** [comment]
Maybe using ant to drive the building with javac would improve the build times?  It invokes javac within it's own JVM these days doesn't it?  The launching and warmup is probably the major overhead.

**Comment by dougxc** [comment]
I don't want to introduce ant into the mix. I've always wondered why javac doesn't have daemon mode.

**Comment by christhalinger** [comment]
In 9 it has.  --enable-javac-server uses it for the 9 build.

**Comment by dougxc** [comment]
Does that require some UnlockExperimentalOptions flag?

```
dsimon@kurz ~/g/graal-core> /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/javac --enable-javac-server
javac: invalid flag: --enable-javac-server
```

**Comment by tkrodriguez** [comment]
I think that's the configure flag to use sjavac in server mode.  Is sjavac going to be an exposed command in 9?

**Comment by christhalinger** [comment]
Sorry, I wasn't clear enough.  This is a configure flag for JDK 9:
```
  --disa ble-javac-server  disable javac server [enabled]
```
Not sure what it actually does.  I think it's a separate Main... yes:

```
$ ./build/macosx-x86_64-normal-server-release/jdk/bin/java com.sun.tools.sjavac.Main
Please specify output directory.
```

**Comment by tkrodriguez** [comment]
I think everyone has wondered about daemon mode for javac since 1.1.  maybe we'll finally get it in JDK9.

I don't like the idea of adding ant to our build mix either but out of curiosity I extracted the javac commands from an mx build and converted that into a build.xml just to do some comparison.  mx -v gate -t Clean,BuildJavaWithJavac takes 2:26, the javac commands from that build executed manually with a shell takes 3:10.  The shell is single threaded which I think accounts for the difference.  using ant with a build.xml derived from those javac commands takes 1:10.

**Comment by dougxc** [comment]
Why is ant so much faster since mx build uses parallelism where as ant doesn't as far as I know? If constructing a temporary build.xml from the build plan constructed by `mx build` is straightforward, it seems like we could get the best of all worlds with [parallel ant](http://blog.codeaholics.org/parallel-ant/).

**Comment by tkrodriguez** [comment]
It surprised me as well.  I think i'm doing it all properly.  I believe it's the warmed up in process javac plus the reduced overhead from the lots of little compiles we do.  There are lots of 1-5 files javac compiles plus several really big ones.  I'll try to reconfirm that ant is really doing all the work it needs to.

**Comment by tkrodriguez** [comment]
It's compiling all the same stuff apart from maybe 2 files.  Blowing away all the class files and generating them from a build.xml produced 8731 class files instead of 8734.  So the work is pretty much equivalent.  I can't test out parallel ant because I don't have dependencies in my build.xml but that would probably be very fast, assuming the in process javac support is thread safe.

**Comment by gilles-duboscq** [comment]
Regarding sjavac, last time i looked, there were problems regarding annotation processors.
Regarding ant: can we use multiple JDK versions inside a single `build.xml`? If not we'd have to build JDK-indexed batches.
If we don't want to depend on ant, it's probably rather easy make a javac deamon. Then we'd just launch one per JDK version needed and just send them work at the point where we normally invoke javac.

**Comment by tkrodriguez** [comment]
I was looking at this on friday and came to the same conclusion.  We'd basically be using ant as a wrapper around javac so we might as well build our own that fits into mx nicely.  I did some experiments with a simple javac daemon.  On my local machine a single threaded BuildJavaWithJavac was 5 minutes, 2 minutes for a regular parallel BuildJavaWithJavac, 1:25 for single threaded javac daemon and 48 seconds with parallel javac daemon.  I'm currently cleaning up the javac daemon sources to add to mx.  The build changes are simple apart from managing the daemons within mx.

**Comment by tkrodriguez** [comment]
The javac and ecj daemon graalvm/mx#72 and graalvm/mx#86 improved compile time considerably.
