### ISSUE TITLE
Error resolving system dependencies on Fedora 23

### ISSUE THREAD

**Issue by noahdesu** [graalvm/graal-core#91]
I'm running `mx build` and hitting some dependency issues:

```bash
Linking vm...
/usr/bin/ld: cannot find -lstdc++

collect2: error: ld returned 1 exit status

/usr/bin/chcon: cannot access ‘libjvm.so’: No such file or directory

ERROR: Cannot chcon libjvm.so
/usr/bin/objcopy: 'libjvm.so': No such file
```

But these dependencies do seem to be satisfied on my system:

```bash
[nwatkins@sapporo graal-core]$ ls -l /usr/lib/jvm/java/jre/lib/amd64/server/ | grep libjvm
-rwxr-xr-x. 1 root root 14124712 Feb 24 10:35 libjvm.so
```

and

```bash
[nwatkins@sapporo graal-core]$ find /usr/lib | grep stdc
/usr/lib/libstdc++.so.6.0.21
/usr/lib/libstdc++.so.6
```

**Comment by rschatz** [comment]
Looks like a development package is not installed. What distribution are you using? Does it have a `gcc-libs-devel` package or something similar?

**Comment by olpaw** [comment]
You can try if installing libstdc++-static and libstdc++-devel helps

**Comment by rschatz** [comment]
I think just `-devel` should be enough. `-static` will probably also work, but just because the build system will fall back on the static lib if it can't find the dynamic one.

**Comment by dougxc** [comment]
http://mail.openjdk.java.net/pipermail/graal-dev/2015-December/004050.html

**Comment by noahdesu** [comment]
Thanks a lot everyone. The static version was required and now it works. If anyone is interested, this is the Dockerfile I am using to reproduce the Graal/Truffle build.

```
FROM fedora:23

RUN dnf -y update && dnf -y install \
    gcc-c++ \
    java-1.8.0-openjdk \
    java-1.8.0-openjdk-devel \
    git \
    python \
    mercurial \
    make \
    findutils \
    libstdc++-static

RUN mkdir /src && cd /src && \
    git clone https://github.com/graalvm/mx.git
ENV PATH /src/mx:$PATH

RUN mkdir /src/graal && cd /src/graal && \
    git clone https://github.com/graalvm/graal-core

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk
ENV DEFAULT_VM server
RUN cd /src/graal/graal-core && \
    mx build && mx vm -version
```

**Comment by olpaw** [comment]
Thanks for sharing your Dockerfile.
